version: "3"
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:$POSTGRES_PORT/$POSTGRES_DB -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -configFiles=/flyway/conf/flyway.config -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5432:${POSTGRES_PORT}"

volumes:
  postgres:
